# -*- coding: utf-8 -*-
"""Final Solution.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1h7Ev_HhojLoXdgrtrH6SQY5T8N8mgMM2

**`QRT Challenge - Reconstruction of Liquid Asset Performance`**

**Approach:** Day-level multi-output MLP with sector-aware features, ensembled with per-target LightGBM.

**Best Public LB:** 0.7471 (rank 72)

## Iteration history

| Version | Approach | OOF | LB |
|---|---|---|---|
| v1 | NN MSE regression, minimal features | 0.6736 | 0.6753 |
| v2 | NN BCE loss (matched to metric), full features | 0.7309 | 0.7387 |
| v3 | NN + LightGBM ensemble (default params) | 0.7439 | 0.7465 |
| v4 | NN + LightGBM ensemble (tuned params) | 0.7448 | **0.7471** |
| v5 | NN + LGBM + XGBoost (3-way blend) | 0.7445 | 0.7469 |

## Key design decisions (justification in interview)

  1. Within each day, all rows share an identical 100-dim feature vector,
     only ID_TARGET differs. So the natural unit of observation is the DAY
     (~2,748 days), not the row (~267,100). Modelling per-day with a
     multi-output head amortizes feature learning across 100 prediction
     tasks — far more sample-efficient than 100 separate target models.

  2. The competition metric is weighted accuracy, where weight = |y|. So
     I train with weighted binary cross-entropy on the sign, with weights
     proportional to |y|. This directly optimizes the eval metric instead
     of a proxy like MSE.

  3. I do GroupKFold splitting on ID_DAY because the test set is held out
     by day. Any random row-level split would put rows from the same day
     in train and validation — given identical features, the model would
     just memorize the day. The leaderboard would then be a brutal surprise.

  4. Sector-aware feature engineering uses the supplementary class
     hierarchy. For each prediction (day, target) I add the mean return
     of illiquid assets that share the target's sector. This is a strong
     inductive prior for cross-sectional asset relationships.

  5. Missingness is handled by zero-imputation + a binary indicator column
     per asset. Zero is the "no move" prior (returns are mean ~0); the
     indicator lets the model decide whether the absence itself is
     informative.

## 1. Setup, imports, data loading
"""

import os
import json
import numpy as np
import pandas as pd
import torch
import torch.nn as nn
from torch.utils.data import DataLoader, TensorDataset
from sklearn.model_selection import GroupKFold
from sklearn.decomposition import PCA
import matplotlib.pyplot as plt

# Reproducibility — set EVERY source of randomness.
SEED = 42
np.random.seed(SEED)
torch.manual_seed(SEED)
torch.cuda.manual_seed_all(SEED)
torch.backends.cudnn.deterministic = True

DEVICE = "cuda" if torch.cuda.is_available() else "cpu"
print(f"Using device: {DEVICE}")

os.makedirs("logs", exist_ok=True)

# Mount Drive (Colab) — if running locally, comment this out and update paths below
from google.colab import drive
drive.mount('/content/drive')

X_TRAIN_PATH= '/content/drive/MyDrive/QRT/X_train_itDkypA.csv'
X_TEST_PATH= '/content/drive/MyDrive/QRT/X_test_Beg4ey3.csv'
y_TRAIN_PATH= '/content/drive/MyDrive/QRT/y_train_3LeeT2g.csv'
SUPP_PATH= '/content/drive/MyDrive/QRT/supplementary_data_Vkoyn8z.csv'

X_train= pd.read_csv(X_TRAIN_PATH, index_col="ID")
y_train= pd.read_csv(y_TRAIN_PATH, index_col="ID")
X_test= pd.read_csv(X_TEST_PATH, index_col="ID")
supp= pd.read_csv(SUPP_PATH)

print(f"X_train shape: {X_train.shape}")
print(f"y_train shape: {y_train.shape}")
print(f"X_test shape: {X_test.shape}")
print(f"Supplementary shape:{supp.shape}")

ret_cols = [c for c in X_train.columns if c.startswith("RET_")]
illiquid_ids = [int(c.split("_")[1]) for c in ret_cols]
liquid_ids = sorted(X_train["ID_TARGET"].unique().tolist())
liq_to_idx = {lid: i for i, lid in enumerate(liquid_ids)}     # 0..99 ordering
N_LIQUID = len(liquid_ids)
N_ILLIQUID = len(illiquid_ids)

print(f"Illiquid return columns (features): {len(ret_cols)}")
print(f"# unique ID_TARGET in train: {X_train['ID_TARGET'].nunique()}")
print(f"# unique ID_DAY   in train: {X_train['ID_DAY'].nunique()}")
print(f"# unique ID_DAY   in test:  {X_test['ID_DAY'].nunique()}")
print(f"# day overlap train/test:   {len(set(X_train['ID_DAY']) & set(X_test['ID_DAY']))}")

"""## 2. EDA - exploratory checks that informed the design

Three things to verify before any modeling:

1. Are the within-day features really identical? (This drives everything else.)
2. What does the missingness pattern look like?
3. How concentrated is the metric weight on large-|y| days?
4. Sanity check on linear baseline — what's the max correlation between any single illiquid and each liquid?
"""

# CRITICAL CHECK — within a day, are the RET_i features identical across rows?
# If yes, we have ~2,748 effective training examples, not 267,100.
sample_day = X_train["ID_DAY"].iloc[0]
day_rows = X_train[X_train["ID_DAY"] == sample_day]
within_day_variance = day_rows[ret_cols].var(axis=0).sum()
print(f"[Structure check] Day {sample_day}: rows = {len(day_rows)}, "
      f"variance across rows for all RET_i columns = {within_day_variance:.2e}")
print("If the variance is ~0, then features are identical within a day.")
print("Effective # training days =", X_train["ID_DAY"].nunique())
print("Avg rows per day =", len(X_train) / X_train["ID_DAY"].nunique())

# Missingness pattern
# To get per-day missingness, take the first row of each day (features are
# identical within a day per the check above).
day_features = X_train.groupby("ID_DAY")[ret_cols].first()
missing_rate_per_asset = day_features.isna().mean().sort_values(ascending=False)

fig, ax = plt.subplots(figsize=(10, 4))
ax.bar(range(len(missing_rate_per_asset)), missing_rate_per_asset.values, width=1.0)
ax.set_xlabel("Illiquid asset index (sorted by missing rate)")
ax.set_ylabel("Fraction of days with missing return")
ax.set_title("Missingness per illiquid asset across training days")
plt.show()

print("\nMissingness summary (per-day basis):")
print(missing_rate_per_asset.describe())
print("Top 10 most-missing illiquid assets:")
print(missing_rate_per_asset.head(10))

# Distribution of returns
all_returns_flat = day_features.values.ravel()
all_returns_flat = all_returns_flat[~np.isnan(all_returns_flat)]

y_returns = y_train["RET_TARGET"].values

fig, ax = plt.subplots(1, 2, figsize=(12, 4))
ax[0].hist(all_returns_flat, bins=200, range=(-0.1, 0.1))
ax[0].set_title("Illiquid return distribution (clipped at ±10%)")
ax[0].set_xlabel("Daily return")
ax[0].set_ylabel("Frequency")

ax[1].hist(y_returns, bins=200, range=(-0.1, 0.1), color="orange")
ax[1].set_title("Liquid target return distribution (clipped at ±10%)")
ax[1].set_xlabel("Daily return")
plt.show()

print(f"\nIlliquid return stats: mean={all_returns_flat.mean():.4e}, "
      f"std={all_returns_flat.std():.4e}, "
      f"P(positive)={(all_returns_flat > 0).mean():.3f}")
print(f"Liquid   return stats: mean={y_returns.mean():.4e}, "
      f"std={y_returns.std():.4e}, "
      f"P(positive)={(y_returns > 0).mean():.3f}")

# The competition metric - what's the upside of weighting by |y|?
# Show how the weight is concentrated in the top quantiles of |y|.
abs_y_sorted = np.sort(np.abs(y_returns))[::-1]
cum_share = np.cumsum(abs_y_sorted) / abs_y_sorted.sum()

fig, ax = plt.subplots(figsize=(6, 4))
ax.plot(np.arange(1, len(cum_share) + 1) / len(cum_share), cum_share)
ax.set_xlabel("Fraction of samples (sorted by |y| descending)")
ax.set_ylabel("Cumulative share of total |y|")
ax.set_title("How concentrated is the metric weight?")
ax.grid(alpha=0.3)
for q in [0.10, 0.20, 0.50]:
    idx = int(q * len(cum_share)) - 1
    ax.annotate(f"top {int(q*100)}% → {cum_share[idx]*100:.1f}%",
                xy=(q, cum_share[idx]), xytext=(q + 0.05, cum_share[idx] - 0.1),
                arrowprops=dict(arrowstyle="->"))
plt.show()

print("\nMetric weight concentration:")
for q in [0.05, 0.10, 0.20, 0.50]:
    idx = int(q * len(abs_y_sorted)) - 1
    print(f"  Top {int(q*100):>2}% of |y| account for {cum_share[idx]*100:5.1f}% of the metric weight")

# Supplementary data - sector hierarchy
print("Supplementary data — sector hierarchy:")
for lvl in [1, 2, 3, 4]:
    col = f"CLASS_LEVEL_{lvl}"
    print(f"  {col}: {supp[col].nunique()} unique buckets")

supp["asset_kind"] = supp["ID_asset"].apply(
    lambda i: "illiquid" if i in illiquid_ids else ("liquid" if i in liquid_ids else "other")
)
print("\nLevel-1 sector breakdown by asset kind:")
print(pd.crosstab(supp["CLASS_LEVEL_1"], supp["asset_kind"]))

# Correlation structure — sanity check for the linear benchmark
# Build the panel: rows = days, columns = ALL 200 assets (illiquid + liquid)
panel = day_features.copy()
liq_panel = (pd.concat([X_train[["ID_DAY", "ID_TARGET"]], y_train], axis=1)
             .pivot_table(index="ID_DAY", columns="ID_TARGET", values="RET_TARGET"))
liq_panel.columns = [f"LIQ_{c}" for c in liq_panel.columns]
panel = panel.join(liq_panel)

corr = panel.corr()
illiquid_cols = [c for c in panel.columns if c.startswith("RET_")]
liquid_cols = [c for c in panel.columns if c.startswith("LIQ_")]

max_corrs = corr.loc[illiquid_cols, liquid_cols].abs().max(axis=0)
fig, ax = plt.subplots(figsize=(6, 4))
ax.hist(max_corrs.values, bins=40)
ax.set_xlabel("Max |correlation| of each liquid asset to any illiquid asset")
ax.set_ylabel("# liquid assets")
ax.set_title("How well can a single illiquid asset predict each liquid?")
plt.show()

print(f"\nMax |corr| per liquid asset: mean={max_corrs.mean():.3f}, "
      f"median={max_corrs.median():.3f}, "
      f"min={max_corrs.min():.3f}, max={max_corrs.max():.3f}")
print("Interpretation: a single illiquid asset typically explains "
      f"~{(max_corrs.mean()**2)*100:.1f}% of the variance of a liquid asset's return. "
      "Combining many illiquid features should do meaningfully better.")

"""## 3. Config

Hyperparameters kept compact and visible so I can explain every one.
"""

CFG = {
    "n_folds": 5,
    "batch_size": 64,           # days per batch (NOT rows)
    "epochs": 60,
    "lr": 1e-3,
    "weight_decay": 1e-4,       # mild L2; large WD hurts in noisy financial data
    "hidden_dims": [512, 256, 128],
    "dropout": 0.30,
    "n_pca": 16,                # # of PCA factors of the illiquid panel
    "patience": 8,              # early stopping patience
    "label_smoothing": 0.02,    # tiny — returns near zero are inherently noisy
}

"""## 4. Reshape to day-level panel

This compresses ~267k rows down to ~2.7k days. Features are identical within a day, so taking the first row is loss-less.
"""

def build_day_panel(X):
    """Return (day_features [n_days, N_ILLIQUID], day_ids [n_days])."""
    g = X.groupby("ID_DAY")[ret_cols].first()
    return g.values.astype(np.float32), g.index.values

X_day_train, day_ids_train = build_day_panel(X_train)
X_day_test, day_ids_test = build_day_panel(X_test)
day_to_idx_train = {d: i for i, d in enumerate(day_ids_train)}
day_to_idx_test = {d: i for i, d in enumerate(day_ids_test)}

# Day-level labels: y_panel[d, j] = return of liquid j on day d (NaN if not observed).
print("Building day-level label panel...")
y_panel = np.full((len(day_ids_train), N_LIQUID), np.nan, dtype=np.float32)
joined = pd.concat([X_train[["ID_DAY", "ID_TARGET"]], y_train], axis=1)
for d, dframe in joined.groupby("ID_DAY"):
    d_idx = day_to_idx_train[d]
    for _, row in dframe.iterrows():
        y_panel[d_idx, liq_to_idx[row["ID_TARGET"]]] = row["RET_TARGET"]

mask_panel = (~np.isnan(y_panel)).astype(np.float32)
y_panel_filled = np.where(mask_panel == 1, y_panel, 0.0)
print(f"Label panel shape: {y_panel.shape}, "
      f"observed cells: {mask_panel.sum():.0f} / {mask_panel.size}")

# ---------------------------------------------------------------------------
# LEAKAGE CHECK — permute day-level labels to break the day→target relationship.
# A clean pipeline should score ~0.50 on val with these shuffled labels.
# ---------------------------------------------------------------------------
# LEAKAGE_CHECK = True   # set to False for a real submission
# if LEAKAGE_CHECK:
#     rng = np.random.RandomState(123)
#     perm = rng.permutation(y_panel_filled.shape[0])
#     y_panel_filled = y_panel_filled[perm]
#     mask_panel = mask_panel[perm]
#     print(">>> LEAKAGE CHECK: day-level labels permuted. Expecting val ≈ 0.50.")

"""## 5. Feature engineering

Applied identically to train and test. Every feature is a deterministic function of the day's illiquid panel plus the static supplementary table. No look-ahead.

Five blocks: raw returns, missingness indicators, sector aggregates across 4 hierarchy levels, cross-sectional stats, PCA factors.
"""

class FeatureBuilder:
    """Stateless on val/test except for a fitted PCA on training illiquid returns.

    Note on the supplementary data: it covers BOTH illiquid and liquid asset
    universes. I verified this by checking that all 100 liquid IDs and all
    100 illiquid IDs appear in the supplementary table. So I can do two
    different things with sectors:
      - aggregate the day's illiquid returns by THEIR sector  (market-side feature)
      - look up the TARGET liquid asset's sector              (target-side feature)
    The second is what makes my model target-aware without having to embed
    a target ID. The interaction between the day's sector returns and the
    target's own sector is what carries the signal.
    """

    def __init__(self, supp, illiquid_ids, liquid_ids, n_pca=16):
        self.supp = supp.set_index("ID_asset")
        self.illiquid_ids = illiquid_ids
        self.liquid_ids = liquid_ids
        self.n_pca = n_pca
        # For each level, map illiquid index -> sector id
        self.illiquid_sectors = {
            lvl: np.array([self.supp.loc[i, f"CLASS_LEVEL_{lvl}"] for i in illiquid_ids])
            for lvl in [1, 2, 3, 4]
        }
        self.liquid_sectors = {
            lvl: np.array([self.supp.loc[i, f"CLASS_LEVEL_{lvl}"] for i in liquid_ids])
            for lvl in [1, 2, 3, 4]
        }
        # All unique sectors per level (across both populations) — used to
        # produce a stable column ordering.
        self.all_sectors = {
            lvl: sorted(set(self.illiquid_sectors[lvl].tolist()
                          + self.liquid_sectors[lvl].tolist()))
            for lvl in [1, 2, 3, 4]
        }
        self.pca = None  # fitted in .fit()

    def _impute_and_indicator(self, X_day):
        """Zero-impute returns + append a NaN-indicator column per asset."""
        nan_mask = np.isnan(X_day).astype(np.float32)
        X_filled = np.where(np.isnan(X_day), 0.0, X_day).astype(np.float32)
        return X_filled, nan_mask

    def _sector_means(self, X_filled, nan_mask):
        """For each sector at each level (using the FULL universe of sectors,
        so column ordering is stable), mean of illiquid returns whose sector
        matches. Computed mask-aware so missing returns don't bias the mean.
        Missing sectors (no illiquid asset belongs there) produce a column of 0s,
        which is harmless after normalization."""
        out = []
        for lvl in [1, 2, 3, 4]:
            sec = self.illiquid_sectors[lvl]
            unique = self.all_sectors[lvl]
            agg = np.zeros((X_filled.shape[0], len(unique)), dtype=np.float32)
            for k, s in enumerate(unique):
                cols = np.where(sec == s)[0]
                if len(cols) == 0:
                    continue
                w = 1.0 - nan_mask[:, cols]
                denom = w.sum(axis=1) + 1e-8
                agg[:, k] = (X_filled[:, cols] * w).sum(axis=1) / denom
            out.append(agg)
        return np.concatenate(out, axis=1)

    def _cross_sectional_stats(self, X_filled, nan_mask):
        """Per-day distribution of illiquid returns: mean, std, skew-ish,
        fraction positive. These give the model a sense of 'market regime'."""
        w = 1.0 - nan_mask
        denom = w.sum(axis=1, keepdims=True) + 1e-8
        mean = (X_filled * w).sum(axis=1, keepdims=True) / denom
        var = (((X_filled - mean) ** 2) * w).sum(axis=1, keepdims=True) / denom
        std = np.sqrt(var + 1e-8)
        skewish = (((X_filled - mean) ** 3) * w).sum(axis=1, keepdims=True) / (denom * std**3 + 1e-8)
        frac_pos = ((X_filled > 0) * w).sum(axis=1, keepdims=True) / denom
        return np.concatenate([mean, std, skewish, frac_pos], axis=1).astype(np.float32)

    def fit(self, X_day_train):
        X_filled, _ = self._impute_and_indicator(X_day_train)
        self.pca = PCA(n_components=self.n_pca, random_state=SEED).fit(X_filled)

    def transform(self, X_day):
        X_filled, nan_mask = self._impute_and_indicator(X_day)
        feats = [
            X_filled,                                  # 100
            nan_mask,                                  # 100  (missingness indicators)
            self._sector_means(X_filled, nan_mask),    # ~ (10 + 22 + 49 + 77) = ~158
            self._cross_sectional_stats(X_filled, nan_mask),  # 4
            self.pca.transform(X_filled).astype(np.float32),  # n_pca
        ]
        return np.concatenate(feats, axis=1).astype(np.float32)

fb = FeatureBuilder(supp, illiquid_ids, liquid_ids, n_pca=CFG["n_pca"])
fb.fit(X_day_train)
F_train = fb.transform(X_day_train)
F_test = fb.transform(X_day_test)
print(f"Engineered feature dim: {F_train.shape[1]}")

# Normalize features using TRAIN statistics. Refit per fold inside the CV loop
# would be more correct, but the gain is negligible and obscures the pipeline;
# I'll mention this explicitly in the interview.
mu = F_train.mean(axis=0, keepdims=True)
sd = F_train.std(axis=0, keepdims=True) + 1e-6
F_train = (F_train - mu) / sd
F_test = (F_test - mu) / sd

"""## 6. Model — small MLP with multi-output head

One forward pass produces 100 logits (one per liquid target). The hidden layers learn a shared representation; the output layer specializes per target. Much more sample-efficient than 100 separate per-target models.
"""

class MLP(nn.Module):
    def __init__(self, in_dim, hidden_dims, out_dim, dropout=0.3):
        super().__init__()
        layers = []
        prev = in_dim
        for h in hidden_dims:
            layers += [nn.Linear(prev, h), nn.GELU(),
                       nn.LayerNorm(h), nn.Dropout(dropout)]
            prev = h
        layers += [nn.Linear(prev, out_dim)]
        self.net = nn.Sequential(*layers)

    def forward(self, x):
        return self.net(x)  # logits, shape [B, N_LIQUID]

"""## 7. Loss function — weighted BCE on sign, masked

This is the single most important design choice. The metric is weighted accuracy with weight = |y|, so I train with weighted BCE with weight = |y| × mask. Same shape as the eval function.

Comparison from my iterations:
- v1 used MSE on returns: OOF 0.674, LB 0.675
- v2 switched to this BCE: OOF 0.731, LB 0.738

+57 bps on LB from just changing the loss function. Direct evidence that matching loss to metric matters.
"""

def weighted_masked_bce(logits, y_true, mask, smoothing=0.02):
    """y_true: actual returns (sign + magnitude).
       mask:   1 where y is observed, else 0.
       weight: |y_true| — this aligns optimization with the eval metric.
    """
    target = (y_true > 0).float()
    target = target * (1 - smoothing) + 0.5 * smoothing   # label smoothing
    weight = mask * y_true.abs()
    bce = nn.functional.binary_cross_entropy_with_logits(
        logits, target, reduction="none"
    )
    return (bce * weight).sum() / (weight.sum() + 1e-8)


def weighted_accuracy(logits, y_true, mask):
    """Competition metric — exactly as defined in the spec."""
    pred_sign = torch.sign(logits)         # logits>0 → +1, <0 → -1
    pred_sign[pred_sign == 0] = 1
    true_sign = torch.sign(y_true)
    correct = (pred_sign == true_sign).float() * mask
    weight = mask * y_true.abs()
    return (correct * y_true.abs()).sum() / (weight.sum() + 1e-8)

"""## 8. Cross-validation — GroupKFold by ID_DAY

Two reasons GroupKFold is mandatory here:
1. The test set is split by day. CV should mirror that.
2. Within-day rows have identical features. Random KFold puts identical rows in train and val, so the model memorizes the day signature instead of learning anything. I verified random KFold leaks ~14 points on a Random Forest baseline.

Also ran a label permutation test as a leakage check: shuffled day-level labels to destroy the day→target mapping, retrained the full pipeline, got OOF 0.511 (vs 0.731 unpermuted). That confirms the signal is real.
"""

y_t = torch.from_numpy(y_panel_filled)
m_t = torch.from_numpy(mask_panel)
F_t = torch.from_numpy(F_train)
F_te = torch.from_numpy(F_test)

gkf = GroupKFold(n_splits=CFG["n_folds"])
oof_logits = np.zeros((len(F_train), N_LIQUID), dtype=np.float32)
test_logits_folds = []
fold_scores = []

# We pass day_ids_train as the "groups" so each fold's val days are disjoint
# from train days. (Days are already unique, so this is equivalent to KFold
# on day index — but GroupKFold makes the intent explicit.)
for fold, (tr_idx, va_idx) in enumerate(
        gkf.split(F_train, groups=day_ids_train)):

    print(f"\n===== Fold {fold + 1}/{CFG['n_folds']} =====")
    F_tr, F_va = F_t[tr_idx], F_t[va_idx]
    y_tr, y_va = y_t[tr_idx], y_t[va_idx]
    m_tr, m_va = m_t[tr_idx], m_t[va_idx]

    train_loader = DataLoader(
        TensorDataset(F_tr, y_tr, m_tr),
        batch_size=CFG["batch_size"], shuffle=True, drop_last=False
    )

    model = MLP(F_train.shape[1], CFG["hidden_dims"], N_LIQUID,
                dropout=CFG["dropout"]).to(DEVICE)
    opt = torch.optim.AdamW(model.parameters(),
                            lr=CFG["lr"], weight_decay=CFG["weight_decay"])
    sched = torch.optim.lr_scheduler.CosineAnnealingLR(
        opt, T_max=CFG["epochs"])

    best_va_score = -1.0
    best_state = None
    bad_epochs = 0
    history = {"train_loss": [], "val_score": []}

    for epoch in range(CFG["epochs"]):
        model.train()
        train_loss = 0.0
        n_batches = 0
        for xb, yb, mb in train_loader:
            xb, yb, mb = xb.to(DEVICE), yb.to(DEVICE), mb.to(DEVICE)
            opt.zero_grad()
            logits = model(xb)
            loss = weighted_masked_bce(logits, yb, mb, CFG["label_smoothing"])
            loss.backward()
            torch.nn.utils.clip_grad_norm_(model.parameters(), 1.0)
            opt.step()
            train_loss += loss.item()
            n_batches += 1
        sched.step()
        train_loss /= n_batches

        # Validation
        model.eval()
        with torch.no_grad():
            va_logits = model(F_va.to(DEVICE))
            va_score = weighted_accuracy(va_logits, y_va.to(DEVICE),
                                         m_va.to(DEVICE)).item()
        history["train_loss"].append(train_loss)
        history["val_score"].append(va_score)
        improved = va_score > best_va_score
        marker = " *" if improved else ""
        print(f"  epoch {epoch+1:3d}  loss={train_loss:.5f}  "
              f"val_score={va_score:.5f}{marker}")
        if improved:
            best_va_score = va_score
            best_state = {k: v.detach().cpu().clone()
                          for k, v in model.state_dict().items()}
            bad_epochs = 0
        else:
            bad_epochs += 1
            if bad_epochs >= CFG["patience"]:
                print(f"  early stop at epoch {epoch+1}")
                break

    # Reload best checkpoint, store OOF + test predictions
    model.load_state_dict(best_state)
    model.eval()
    with torch.no_grad():
        oof_logits[va_idx] = model(F_va.to(DEVICE)).cpu().numpy()
        test_logits_folds.append(model(F_te.to(DEVICE)).cpu().numpy())
    fold_scores.append(best_va_score)
    print(f"  fold {fold+1} best val score: {best_va_score:.5f}")

    # Save training curve for this fold
    fig, ax = plt.subplots(1, 2, figsize=(10, 3))
    ax[0].plot(history["train_loss"])
    ax[0].set_title(f"Fold {fold+1} train loss")
    ax[0].set_xlabel("epoch")
    ax[1].plot(history["val_score"])
    ax[1].set_title(f"Fold {fold+1} val weighted accuracy")
    ax[1].set_xlabel("epoch")
    ax[1].axhline(0.5, ls="--", color="gray")
    fig.savefig(f"logs/fold{fold+1}_curves.png", bbox_inches="tight")
    plt.show()

"""## 9. OOF score and NN test predictions"""

# OOF metric — apples-to-apples honest estimate of leaderboard score
oof_score = weighted_accuracy(
    torch.from_numpy(oof_logits), y_t, m_t).item()
print(f"\nOOF weighted accuracy: {oof_score:.5f}")
print(f"Per-fold scores: {fold_scores}")
print(f"  mean = {np.mean(fold_scores):.5f}  "
      f"std = {np.std(fold_scores):.5f}")

with open("cv_scores.json", "w") as f:
    json.dump({"fold_scores": fold_scores,
               "oof_score": oof_score,
               "cfg": CFG}, f, indent=2)

# Test predictions — average the 5 fold models' logits, then take sign.
# Logit-averaging is equivalent to log-odds averaging; cleaner than
# probability-averaging because we never need to call sigmoid.
test_logits_mean = np.mean(test_logits_folds, axis=0)

# Map back from (day, target) to row-level predictions
preds = np.zeros(len(X_test), dtype=np.int64)
for k, (test_id, row) in enumerate(X_test.iterrows()):
    d_idx = day_to_idx_test[row["ID_DAY"]]
    j_idx = liq_to_idx[row["ID_TARGET"]]
    logit = test_logits_mean[d_idx, j_idx]
    preds[k] = 1 if logit > 0 else -1

submission = pd.DataFrame({
    "ID": X_test.index.values,
    "RET_TARGET": preds
})
submission.to_csv("submission.csv", index=False)
print(f"\nWrote submission.csv with {len(submission)} rows")
print(f"Sign distribution: +1 = {(preds == 1).sum()}, "
      f"-1 = {(preds == -1).sum()}")

# Save NN predictions for the LightGBM ensemble
np.save("nn_oof_logits.npy", np.asarray(oof_logits, dtype=np.float32))
np.save("nn_test_logits.npy", np.asarray(test_logits_mean, dtype=np.float32))
print("Saved NN OOF and test logits for ensemble step.")

"""## 10. LightGBM as a second model, then ensemble with NN

Trains a per-target LightGBM with the SAME features and SAME GroupKFold splits as the NN, then z-normalizes both models' OOF and test predictions and averages them. The optimal blend weight is found by sweeping on OOF.

**Why ensemble:** NN and GBDT make different mistakes. NN learns smooth representations via gradient descent; GBDT learns rule-like splits. Their errors are partially decorrelated. Averaging reduces variance.

**Tuned LGBM hyperparameters** (vs defaults):
- `lr=0.03` (was 0.05): slower learning, more rounds, better generalization
- `num_leaves=15` (was 31): smaller trees prevent overfit on 2200 samples
- `min_data_in_leaf=80` (was 40): more conservative
- `feature_fraction=0.6` (was 0.8): more random subspace = more diversity per tree
- `lambda_l1=0.5, lambda_l2=2.0`: stronger regularization for small noisy data
- `N_ROUNDS=400` (was 200): compensate for lower learning rate

Tuned version gave LB 0.7471 vs 0.7465 with defaults.
"""

import lightgbm as lgb
from joblib import Parallel, delayed

print("\n" + "="*72)
print("Starting LightGBM ensemble pipeline")
print("="*72)

# Sanity: reuse F_train, F_test, y_panel_filled, mask_panel, day_ids_train
# from the NN section above. Don't refit FeatureBuilder.
assert F_train.shape[0] == y_panel_filled.shape[0], "Feature/label mismatch"

# Load NN predictions we just saved
nn_oof = np.load("nn_oof_logits.npy")
nn_test = np.load("nn_test_logits.npy")
print(f"NN OOF shape: {nn_oof.shape}, NN test shape: {nn_test.shape}")



# Per-target LightGBM — tuned hyperparameters
LGBM_PARAMS = dict(
    objective="regression_l1",     # L1 loss is robust to fat tails in returns
    learning_rate=0.03,            # slower learning, more rounds, better generalization
    num_leaves=15,                 # smaller trees prevent overfit on 2200 samples
    min_data_in_leaf=80,           # more conservative, less overfit
    feature_fraction=0.6,          # more random subspace = more diversity per tree
    bagging_fraction=0.7,
    bagging_freq=3,
    lambda_l1=0.5,                 # light L1 regularization
    lambda_l2=2.0,                 # stronger L2 for small data
    min_gain_to_split=0.0,
    verbose=-1,
)
N_ROUNDS = 200
N_FOLDS = 5

gkf = GroupKFold(n_splits=N_FOLDS)
lgbm_oof = np.zeros_like(nn_oof)
lgbm_test = np.zeros_like(nn_test)

def train_one_target(j, F_tr, y_tr, m_tr, F_va, F_te, params, n_rounds):
    """Train LGBM for one target, return (j, val_pred, test_pred)."""
    m = m_tr[:, j] == 1
    if m.sum() < 50:
        return j, None, None
    weights = np.abs(y_tr[m, j])
    train_set = lgb.Dataset(F_tr[m], y_tr[m, j], weight=weights)
    booster = lgb.train(params, train_set, num_boost_round=n_rounds)
    return j, booster.predict(F_va), booster.predict(F_te)

# Set internal threads to 1 since we're parallelizing across targets externally
LGBM_PARAMS_PARALLEL = {**LGBM_PARAMS, "num_threads": 1, "verbose": -1}

for fold, (tr_idx, va_idx) in enumerate(gkf.split(F_train, groups=day_ids_train)):
    print(f"\n===== LGBM Fold {fold+1}/{N_FOLDS} =====")

    F_tr_fold = F_train[tr_idx]
    F_va_fold = F_train[va_idx]
    y_tr_fold = y_panel_filled[tr_idx]
    m_tr_fold = mask_panel[tr_idx]

    # Train all 100 target models in parallel
    results = Parallel(n_jobs=-1, backend="loky", verbose=1)(
        delayed(train_one_target)(
            j, F_tr_fold, y_tr_fold, m_tr_fold,
            F_va_fold, F_test, LGBM_PARAMS_PARALLEL, N_ROUNDS
        )
        for j in range(N_LIQUID)
    )

    test_preds_fold = np.zeros_like(nn_test)
    for j, val_pred, test_pred in results:
        if val_pred is not None:
            lgbm_oof[va_idx, j] = val_pred
            test_preds_fold[:, j] = test_pred

    lgbm_test += test_preds_fold / N_FOLDS
    print(f"  fold {fold+1} done")

# Save LGBM predictions
np.save("lgbm_oof.npy", lgbm_oof)
np.save("lgbm_test.npy", lgbm_test)

# Compute LGBM standalone OOF score
def weighted_acc(scores, y, mask):
    pred_sign = np.where(scores > 0, 1.0, -1.0)
    true_sign = np.sign(y); true_sign[true_sign == 0] = 1
    correct = (pred_sign == true_sign).astype(np.float32) * mask
    return (correct * np.abs(y)).sum() / ((mask * np.abs(y)).sum() + 1e-8)

print(f"\nNN-only OOF:   {weighted_acc(nn_oof, y_panel_filled, mask_panel):.5f}")
print(f"LGBM-only OOF: {weighted_acc(lgbm_oof, y_panel_filled, mask_panel):.5f}")

# Z-normalize before blending (different models have different scales)
def z_norm(x):
    return (x - x.mean()) / (x.std() + 1e-8)

nn_oof_z = z_norm(nn_oof)
lgbm_oof_z = z_norm(lgbm_oof)
nn_test_z = z_norm(nn_test)
lgbm_test_z = z_norm(lgbm_test)

# Sweep blend weight on OOF
print("\n--- Blend weight sweep ---")
best_w, best_score = 0.5, -1.0
for w in np.linspace(0.0, 1.0, 21):
    blended = w * nn_oof_z + (1 - w) * lgbm_oof_z
    score = weighted_acc(blended, y_panel_filled, mask_panel)
    print(f"  w_nn={w:.2f}: OOF={score:.5f}")
    if score > best_score:
        best_score, best_w = score, w

print(f"\nBest blend: w_nn={best_w:.2f}, OOF={best_score:.5f}")

# Build submission with the best blend
final_test_score = best_w * nn_test_z + (1 - best_w) * lgbm_test_z

preds = np.zeros(len(X_test), dtype=np.int64)
for k, (test_id, row) in enumerate(X_test.iterrows()):
    d_idx = day_to_idx_test[row["ID_DAY"]]
    j_idx = liq_to_idx[row["ID_TARGET"]]
    preds[k] = 1 if final_test_score[d_idx, j_idx] > 0 else -1

submission = pd.DataFrame({"ID": X_test.index.values, "RET_TARGET": preds})
submission.to_csv("submission_ensemble.csv", index=False)
print(f"\nWrote submission_ensemble.csv  |  +1: {(preds==1).sum()}, -1: {(preds==-1).sum()}")

"""##XGB as a Third model, then ensemble"""

import xgboost as xgb

XGB_PARAMS = dict(
    objective="reg:absoluteerror",
    learning_rate=0.03,
    max_depth=5,
    min_child_weight=10,
    subsample=0.7,
    colsample_bytree=0.7,
    reg_alpha=0.5,
    reg_lambda=1.0,
    tree_method="hist",
    verbosity=0,
    nthread=1,
)
XGB_ROUNDS = 200

xgb_oof = np.zeros_like(nn_oof)
xgb_test = np.zeros_like(nn_test)

def train_one_xgb(j, F_tr, y_tr, m_tr, F_va, F_te):
    m = m_tr[:, j] == 1
    if m.sum() < 50:
        return j, None, None
    weights = np.abs(y_tr[m, j])
    dtrain = xgb.DMatrix(F_tr[m], label=y_tr[m, j], weight=weights)
    dval = xgb.DMatrix(F_va)
    dtest = xgb.DMatrix(F_te)
    booster = xgb.train(XGB_PARAMS, dtrain, num_boost_round=XGB_ROUNDS)
    return j, booster.predict(dval), booster.predict(dtest)

for fold, (tr_idx, va_idx) in enumerate(gkf.split(F_train, groups=day_ids_train)):
    print(f"\n===== XGB Fold {fold+1}/5 =====")
    F_tr_fold = F_train[tr_idx]; F_va_fold = F_train[va_idx]
    y_tr_fold = y_panel_filled[tr_idx]; m_tr_fold = mask_panel[tr_idx]

    results = Parallel(n_jobs=-1)(
        delayed(train_one_xgb)(j, F_tr_fold, y_tr_fold, m_tr_fold,
                                F_va_fold, F_test)
        for j in range(N_LIQUID)
    )

    test_preds_fold = np.zeros_like(nn_test)
    for j, val_pred, test_pred in results:
        if val_pred is not None:
            xgb_oof[va_idx, j] = val_pred
            test_preds_fold[:, j] = test_pred
    xgb_test += test_preds_fold / 5
    print(f"  fold {fold+1} done")

print(f"\nXGB-only OOF: {weighted_acc(xgb_oof, y_panel_filled, mask_panel):.5f}")

# Z-normalize XGB
xgb_oof_z = z_norm(xgb_oof)
xgb_test_z = z_norm(xgb_test)

# Three-way blend sweep: NN + LGBM + XGB, weights sum to 1
print("\n--- Three-way blend sweep ---")
best_score = -1.0
best_w_nn, best_w_lgbm = 0.33, 0.33
for w_nn in np.linspace(0.0, 1.0, 11):
    for w_lgbm in np.linspace(0.0, 1.0 - w_nn, 11):
        w_xgb = 1.0 - w_nn - w_lgbm
        if w_xgb < 0: continue
        blended = w_nn * nn_oof_z + w_lgbm * lgbm_oof_z + w_xgb * xgb_oof_z
        score = weighted_acc(blended, y_panel_filled, mask_panel)
        if score > best_score:
            best_score, best_w_nn, best_w_lgbm = score, w_nn, w_lgbm

best_w_xgb = 1.0 - best_w_nn - best_w_lgbm
print(f"Best 3-way blend: w_nn={best_w_nn:.2f}, w_lgbm={best_w_lgbm:.2f}, "
      f"w_xgb={best_w_xgb:.2f}, OOF={best_score:.5f}")

# Apply to test
final_test_score = (best_w_nn * nn_test_z +
                    best_w_lgbm * lgbm_test_z +
                    best_w_xgb * xgb_test_z)

preds = np.zeros(len(X_test), dtype=np.int64)
for k, (test_id, row) in enumerate(X_test.iterrows()):
    d_idx = day_to_idx_test[row["ID_DAY"]]
    j_idx = liq_to_idx[row["ID_TARGET"]]
    preds[k] = 1 if final_test_score[d_idx, j_idx] > 0 else -1

submission = pd.DataFrame({"ID": X_test.index.values, "RET_TARGET": preds})
submission.to_csv("submission_3way_ensemble.csv", index=False)
print(f"Wrote 3-way submission")

"""\## 11. What I also tried (negative results worth mentioning)

**MSE regression on returns (v1):** OOF 0.674, LB 0.675. Worse than BCE on sign by ~57 bps on LB. Match loss to metric.

**Random KFold on row-level data:** Scores ~0.65 on RF in CV but the test set crashes back to ~0.51. Within-day identical features = leakage. Always use GroupKFold by ID_DAY.

**Seed-averaged NN (3 seeds):** OOF improved by ~9 bps but LB dropped 5 bps vs single-seed. OOF-LB gap widened. Concluded this was statistical noise from the small public LB; reverted to single-seed best.

**LightGBM with default hyperparameters:** OOF 0.7407, LB 0.7465. Tuned version (above) is +6 bps on LB.

**Label permutation test** (leakage check): shuffled day-level labels, retrained full pipeline, got OOF 0.511. Confirms no significant leakage in the pipeline.

## Final results

- **Best public LB:** 0.7471 (rank 72)
- **OOF score:** 0.7448 (gap of +23 bps OOF→LB, within noise tolerance)
- **Benchmark (QRT paired-beta):** 0.5110
- **Trivial constant predictor:** ~0.520
"""

